development:
  bucket: zounds-dev
  access_key_id: AKIAIDQFQL6U46ZQT3AA
  secret_access_key: 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
test:
  bucket: zounds-test
  access_key_id: AKIAIDQFQL6U46ZQT3AA
  secret_access_key: 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
production:
  bucket: zounds-pro
  access_key_id: AKIAIDQFQL6U46ZQT3AA
  secret_access_key: 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